services:
  mongo:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data: